### ISSUE TITLE
Unwanted CSS markup from snake game

### ISSUE THREAD

**Issue by BrechtA** [IcToxi/dash-grocery#96]
Hi, 

I'd like to use this library for the Stars module.
When I import this module it seems to add some unwanted mark-up to my dash application though.
There's an unwanted margin of 20 that gets added for buttons, overwriting my external css sheet.

I think the components of this directory should be better containerized.
If I use 'from dash_grocery import Stars' I shouldn't be struggling with markup that is applied on some unrelated Snake game.

I'm not sure if this directory is still maintained but I would be very thankful if someone could have a look at this.

![image](https://github.com/IcToxi/dash-grocery/assets/5300405/0b2547be-19ef-40fb-81ba-488d54434a3d)

**Comment by IcToxi** [comment]
Hi there,
Sorry that I don't have time to maintain it recently. However, this project is mainly for learning. You may consider forking it and removing the parts you don't need in your own project. Or maybe you are interested in maintaining this library together?

**Comment by BrechtA** [comment]
Hi @IcToxi ,

Thank you so much for your fast reply, sadly the notification came to my spam, so I didn't see it before.
I've checked it again and some CSS gets added to my dash application that seems related to the game, despite only importing the Stars module.
It does affect all buttons as shown here:
.game-splash div, **button** {
    margin: 20px 0;
}

I cloned the repo and tried to search where this CSS gets added, but a literal search didn't yield any results.
I assume the css is dynamically generated somewhere, I'd love to help but my knowledge of javascript is limited and rusty.
Any further help would be highly appreciated!

**Full style element that gets added:**

<style>.snake-container {
    text-align: center;
}

.game-border {
    -webkit-box-shadow: 0px 0px 23px 0px rgba(0,0,0,0.75);
    -moz-box-shadow: 0px 0px 23px 0px rgba(0,0,0,0.75);
    box-shadow: 0px 0px 23px 0px rgba(0,0,0,0.75);
    margin: auto;
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: center;
    position: relative;
}

.point-bar {
    margin: 5px auto;
    text-align: right;
}

.game-splash {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    background-color: #000000d5;
}

.game-splash div, button {
    margin: 20px 0;
}

.game-splash div {
    font-size: 60px;
    color: white;
}

.game-splash button {
    padding: 10px 20px;
    border-radius: 5px;
    border: 1px solid black;
    background-color: #248ec2;
    color: white;
    font-family: 'East Sea Dokdo', cursive;
    font-size: 25px;
    transition: 0.5s;
}

.game-splash button:hover {
    background-color: white;
    cursor: pointer;
    color: black;
}

.snake-mobile-buttons {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}

.snake-mobile-buttons div {
    display: flex;
    flex-direction: row;
    justify-content: space-evenly;
    align-items: center;
    width: 100%;
}

.snake-mobile-buttons div button {
    margin: 5px 100px;
    padding: 8px 20px;
    border-radius: 0;
    border: 1px solid black;
}</style>

**Comment by IcToxi** [comment]
Hi @BrechtA,

you may consider to comment out the content you don't need after line 18 of `src/lib/index.js` and repackaging it. 

Hope this helps you.

**Comment by BrechtA** [comment]
Hi @IcToxi ,

Thanks for the info!
I took a look at this and am starting to better understand the structure of the project.
Each module in `src/lib/components/` loads a react project, potentially loading CSS mark-up (I went to look in the Snake repo (https://github.com/derrmru/react-snake) and found the 'perpetrating' CSS code.

I understand your solution of commenting out the exports in index.js, but this really feels like a 'bandage' than a fix.
I have no experience with these kind of projects but did some iterations with ChatGPT, which proposes to structure the index.js as below to allow individual components to be exported.
Do you think this is a feasible approach?

export { default as LazyLoad } from './components/lazy_load';
export { default as QRCodeSVG } from './components/qrcode/QRCodeSVG';
export { default as QRCodeCanvas } from './components/qrcode/QRCodeCanvas';
export { default as Barcode } from './components/barcode/Barcode';
export { default as MouseParticles } from './components/particles/MouseParticles';
export { default as ParticlesBg } from './components/particles/ParticlesBg';
export { default as PowerModeInput } from './components/particles/PowerModeInput';
export { default as Weather } from './components/weather';
export { default as Textfit } from './components/textfit';
export { default as Clock } from './components/clock';
export { default as Snake } from './components/games/snake';
export { default as Masonry } from './components/masonry';
export { default as Stars } from './components/stars';

**Comment by IcToxi** [comment]
hi @BrechtA ,

forgot to mention that you can also comment out the `import` lines and the dependencies in `package.json`.

and no worries, it won't be a bandage solution. All these changes just to tell the packager to ignore the components you don't need and will not affect the python lib you finally use.

actually you can remove all the lines and components folders that are useless to you.

**Comment by IcToxi** [comment]
removed.
